theme: jekyll-theme-leap-day
show_downloads: true

title: Palefill
description: Web Technologies Polyfill
logo_icon: icon64.png

github:
  release_url: https://github.com/martok/palefill/releases/latest
  install_url: https://github.com/martok/palefill/releases/download/v1.22/palefill-1.22.xpi
